export const CREATE_COMMUNITY = "CREATE_COMMUNITY";

export const GET_COMMUNITY = "GET_COMMUNITY";
export const STORE_COMMUNITY = "STORE_COMMUNITY";

export const GET_TRENDING_COMMUNITIES = "GET_TRENDING_COMMUNITIES";
export const STORE_TRENDING_COMMUNITIES = "STORE_TRENDING_COMMUNITIES";

export const UPDATE_COMMUNITY = "UPDATE_COMMUNITY";

export const GET_ROLES_LOGGED_IN_USER = "GET_ROLES_LOGGED_IN_USER";
export const STORE_ROLES_LOGGED_IN_USER = "STORE_ROLES_LOGGED_IN_USER";

export const JOIN_COMMUNITY = "JOIN_COMMUNITY";
export const LEAVE_COMMUNITY = "LEAVE_COMMUNITY";