export const CREATE_COMMUNITY = "CREATE_COMMUNITY";

export const GET_COMMUNITY = "GET_COMMUNITY";
export const STORE_COMMUNITY = "STORE_COMMUNITY";

export const UPDATE_COMMUNITY = "UPDATE_COMMUNITY";

export const GET_ROLES_LOGGED_IN_USER = "GET_ROLES_LOGGED_IN_USER";
export const STORE_ROLES_LOGGED_IN_USER = "STORE_ROLES_LOGGED_IN_USER";

export const GET_BANNED_USERS = "GET_BANNED_USERS";
export const STORE_BANNED_USERS = "STORE_BANNED_USERS";
export const GET_MODERATORS = "GET_MODERATORS";
export const STORE_MODERATORS = "STORE_MODERATORS";

export const JOIN_COMMUNITY = "JOIN_COMMUNITY";
export const LEAVE_COMMUNITY = "LEAVE_COMMUNITY";

export const MODERATION = {
    PROMOTE_MEMBER: "PROMOTE_MEMBER",
    BAN_MEMBER: "BAN_MEMBER",
    UNBAN_MEMBER: "UNBAN_MEMBER",
    DELETE_POST: "DELETE_POST",
}