export const GET_POST = "GET_POST"
export const STORE_POST = "STORE_POST"
export const GET_COMMENTS = "GET_COMMENTS"
export const STORE_COMMENTS = "STORE_COMMENTS"
export const POST_COMMENT = "POST_COMMENT"