export const SEARCH_USERS = "SEARCH_USERS"
export const STORE_SEARCHED_USERS = "STORE_SEARCHED_USERS"
export const DO_FOLLOW_SEARCHED_USER = "DO_FOLLOW_SEARCHED_USER"
export const DO_UNFOLLOW_SEARCHED_USER = "DO_UNFOLLOW_SEARCHED_USER"

export const SEARCH_COMMUNITIES = "SEARCH_COMMUNITIES"
export const STORE_SEARCHED_COMMUNITIES = "STORE_SEARCHED_COMMUNITIES"
export const DO_JOIN_SEARCHED_COMMUNITY = "DO_JOIN_SEARCHED_COMMUNITY"
export const DO_LEAVE_SEARCHED_COMMUNITY = "DO_LEAVE_SEARCHED_COMMUNITY"

export const SEARCH_POSTS = "SEARCH_POSTS"
export const STORE_SEARCHED_POSTS = "STORE_SEARCHED_POSTS"
export const CLEAR_SEARCHED_POSTS = "CLEAR_SEARCHED_POSTS"
export const DO_LIKE_SEARCHED_POST = "DO_LIKE_SEARCHED_POST";
export const DO_UNLIKE_SEARCHED_POST = "DO_UNLIKE_SEARCHED_POST"


export const STORE_SEARCHED_USERS_COMMUNITIES_FILTER = "STORE_SEARCHED_USERS_COMMUNITIES_FILTER"
export const USERS_COMMUNITIES_FILTER = {
    ALL: "all",
    USERS: "users",
    COMMUNITIES: "communities"
}
export const STORE_SEARCHED_POSTS_SORT_TYPE = "STORE_SEARCHED_POSTS_SORT_TYPE"
export const POSTS_SORT_TYPE = {
    TIMESTAMP: "timestamp",
    LIKES: "likes"
}
