export const GET_TRENDING_USERS = "GET_TRENDING_USERS"
export const STORE_TRENDING_USERS = "STORE_TRENDING_USERS"
export const DO_FOLLOW_TRENDING_USER = "DO_FOLLOW_TRENDING_USER"
export const DO_UNFOLLOW_TRENDING_USER = "DO_UNFOLLOW_TRENDING_USER"

export const GET_TRENDING_COMMUNITIES = "GET_TRENDING_COMMUNITIES"
export const STORE_TRENDING_COMMUNITIES = "STORE_TRENDING_COMMUNITIES"
export const DO_JOIN_TRENDING_COMMUNITY = "DO_JOIN_TRENDING_COMMUNITY"
export const DO_LEAVE_TRENDING_COMMUNITY = "DO_LEAVE_TRENDING_COMMUNITY"