export const GET_TRENDING_USERS = "GET_TRENDING_USERS"
export const STORE_TRENDING_USERS = "STORE_TRENDING_USERS"

export const GET_TRENDING_COMMUNITIES = "GET_TRENDING_COMMUNITIES"
export const STORE_TRENDING_COMMUNITIES = "STORE_TRENDING_COMMUNITIES"