export const GET_LOGIN_NONCE = "GET_LOGIN_NONCE"
export const STORE_LOGIN_NONCE = "STORE_LOGIN_NONCE"
export const LOGIN_USER = "LOGIN_USER"

export const GET_LOGGED_IN_USER = "GET_LOGGED_IN_USER"
export const STORE_LOGGED_IN_USER = "STORE_LOGGED_IN_USER"

export const DO_JOIN_LOGGED_IN_USER_COMMUNITY = "DO_JOIN_LOGGED_IN_USER_COMMUNITY"
export const DO_LEAVE_LOGGED_IN_USER_COMMUNITY = "DO_LEAVE_LOGGED_IN_USER_COMMUNITY"

export const GET_NFT = "GET_NFT"
export const STORE_NFT = "STORE_NFT"
export const GET_FUNDS = "GET_FUNDS"
export const STORE_FUNDS = "STORE_FUNDS"
export const UPDATE_DASHBOARD = "UPDATE_DASHBOARD"

export const GET_USER = "GET_USER"
export const GET_USERS = "GET_USERS"
export const STORE_USER = "STORE_USER"
export const STORE_USERS = "STORE_USERS"

export const CREATE_USER = "CREATE_USER"
export const UPDATE_USER = "UPDATE_USER"

export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS"
export const STORE_NOTIFICATIONS = "STORE_NOTIFICATIONS"
export const STORE_UNREADSTATUS = "STORE_UNREADSTATUS"

export const FOLLOW_USER = "FOLLOW_USER"
export const UNFOLLOW_USER = "UNFOLLOW_USER"